### ISSUE TITLE
Sort by usWeightClass

### ISSUE THREAD

**Issue by Kris-Sowersby** [maxesnee/stack-and-justify#1]
The current sorting seems to be by name. It would be great if it sorted by `usWeightClass` if possible.

**Comment by maxesnee** [comment]
Yes, I agree. 
That would require parsing the font files, but I was planning on using opentype.js to detect OT features anyway.

I add it to my todo list for the next update.

**Comment by maxesnee** [comment]
This is now implemented in v1.10. It is online now.

Sorting now works like this: `familyName` > `usWidthClass` > `usWeightClass`
