### ISSUE TITLE
Feature Request: Detect & Toggle OT Features

### ISSUE THREAD

**Issue by ibo-o** [maxesnee/stack-and-justify#2]
Hey Max, do you still consider [adding support](https://github.com/maxesnee/stack-and-justify/issues/1#issuecomment-1976240210) for OT Features? 
@HirbodLotfian and I think that would be very nice.

**Comment by maxesnee** [comment]
Hi Ibrahim ! Yes I do, I just haven't had time to do it yet. I hope to do it in august : )

**Comment by maxesnee** [comment]
It took a little longer than I planned, but it is now working in the last update.
It is online now, you may have to clear the cache of your browser to see it.
https://max-esnee.com/stack-and-justify/

Let me know if everything works for you!

**Comment by andreirobu** [comment]
For some reason the site won't load for me. It's a blank page.

**Comment by maxesnee** [comment]
What browser do you use ?
Also, if you could open the developer console (CMD+Option+I)  and tell me if you see any error message, that would be helpful.

**Comment by andreirobu** [comment]
I'm on Safari.

<img width="1510" alt="Screenshot 2024-08-27 at 16 06 21" src="https://github.com/user-attachments/assets/dab9c17f-e93a-44eb-ae1d-4085052a1f27">

**Comment by maxesnee** [comment]
Looks like it's a cache problem.
You can empty the cache in Safari with CMD+Option+E. Then reload the page and tell me

**Comment by andreirobu** [comment]
You're right. It worked!
Thanks for this tool. Using it on a daily basis!

**Comment by ibo-o** [comment]
> It took a little longer than I planned, but it is now working in the last update. It is online now, you may have to clear the cache of your browser to see it. https://max-esnee.com/stack-and-justify/
> 
> Let me know if everything works for you!

Works like a charm! Thank you Max🥰

**Comment by maxesnee** [comment]
@andreirobu @ibo-o Great, thank you : )
